title: RX-HCM Grid Node 01
description: Autonomous Knowledge Expansion Node of HCM Engine
theme: jekyll-theme-cayman
markdown: kramdown

collections:
  summaries:
    output: true
    permalink: /summaries/:name
